version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tfcManagerRoot
      MYSQL_DATABASE: tfcManager
      MYSQL_USER: tfcManager01
      MYSQL_PASSWORD: tfcManager01
    volumes:
      - db-data:/var/lib/mysql:delegated
      - ./BD/gisbertBanyo_DB.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: